### ISSUE TITLE
CSS Edits

### ISSUE THREAD

**Issue by gadenbuie** [tgerke/build-your-own-universe#2]
```css
/* moffitt-xaringan-extra.css */

.talk-title h1 {
  font-weight: 600;
}

.talk-author {
  font-weight: 300;
}

.talk-meta p {
  color: #444;
}

.talk-date {
  font-weight: 300;
}
```

**Comment by gadenbuie** [comment]
For slides from https://github.com/tgerke/ci4cc-cdsc/

```css
.people__label {
  opacity: 0;
  transition: opacity 0.5s ease-in-out;
}

.people__group .weepeople {
  transition: transform 0.5s ease-in-out;
}

.people__group:hover .people__label {
  overflow: ;
  opacity: 1;
}

.people__group:hover .weepeople {
  transform: scale(1.5);
}
```
